apiVersion: v1
kind: Service
metadata:
    name: tryyangcsfrontendmanagementsystem
spec:
    type: LoadBalancer
    ports:
    - port: 3001 
    selector:
        app: tryyangcsfrontendmanagementsystem