apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress3
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      - path: /user(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: users
            port:
              number: 3001
      - path: /assignment/api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: assignment
            port:
              number: 8080
      - path: /grading/api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: grading
            port:
              number: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: frontend
        image: fmdevsimages.azurecr.io/cs3213-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: users
spec:
  ports:
  - name: http
    port: 3001
    targetPort: 3001
  selector:
    app: users
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: users
        image: fmdevsimages.azurecr.io/cs3213-users:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: assignment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: assignment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assignment
  template:
    metadata:
      labels:
        app: assignment
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: assignment
        image: fmdevsimages.azurecr.io/cs3213-assignment:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: grading
spec:
  ports:
  - name: http
    port: 8088
    targetPort: 8088
  selector:
    app: grading
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grading
  template:
    metadata:
      labels:
        app: grading
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: grading
        image: fmdevsimages.azurecr.io/cs3213-grading:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8088